### ISSUE TITLE
How do you use Birt in combination with OpenERP

### ISSUE THREAD

**Issue by sferket** [vaab/report_birt#4]
Now that we are able to call Birt reports from OpenERP, that brings us to the next stage. 

As far as I can oversee we have 2 methods of getting data from OpenERP into Birt:
1. Have Birt query the Postgres DB using JDBC
2. Have Birt access the OpenERP objects using XMLRPC

We would be in favour for option 2. This would give us more security and also access to all object data, also fields that are not in the database. 

How have you used Birt in combination with OpenERP?

**Comment by vaab** [comment]
Our client chose solution 1. But I think solution 2 is better but may lack real out-of-the-box support from BIRT side. I don't know exactly what are the libraries that exists in Java to make XMLRPC calls and how they play nice with BIRT.

Solution 2 seems definitively the best to me, but I didn't experimented it myself. It seems solution 1 is much easier as BIRT as a limited support of database query. I'm no Java guru, so I will come short for any help on this topic.
